name: NOAA Data Ingestion to S3
 
on:
  push:
    branches:
      - dev 
  schedule:
    - cron: "0 6 * * *"  
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start Date (YYYY-MM-DD)'
        required: false
      end_date:
        description: 'End Date (YYYY-MM-DD)'
        required: false

 
jobs:
  ingest_noaa_data:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Calculate dynamic dates
        run: |
          if [ -z "${{ github.event.inputs.start_date }}" ]; then
            echo "START_DATE=$(date -u --date='yesterday' '+%Y-%m-%d')" >> $GITHUB_ENV
          else
            echo "START_DATE=${{ github.event.inputs.start_date }}" >> $GITHUB_ENV
          fi
          
          if [ -z "${{ github.event.inputs.end_date }}" ]; then
            echo "END_DATE=$(date -u '+%Y-%m-%d')" >> $GITHUB_ENV
          else
            echo "END_DATE=${{ github.event.inputs.end_date }}" >> $GITHUB_ENV
          fi  
 
      - name: Run NOAA Ingestion Script
        env:
          NOAA_API_TOKEN: ${{ secrets.NOAA_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: python ingest_noaa_to_s3.py --start_date $START_DATE --end_date $END_DATE